### ISSUE TITLE
problems with the 

### ISSUE THREAD

**Issue by marconr9** [mario-peters/Domoticz-Home-Connect-Plugin#10]
hi,o

I have problems to configure the  homeconnectSSE.sh file.
In the file you have to change 3 lines 
PYTHON_PATH 
Is that directory of the plugin ?
DIR ?
DAEMON=$DIR/homeconnectSSE.py <- is hat right
DEVICE_NAME=<Dishwasher> <--- yes i have dishwasser 
DOMOTICZ_IP (ip adress of my domoticz
Port is the standaart poort of Domoticz ?
Is there any thing more that i have to change.

**Comment by LorDHarA** [comment]
Daemon user?

see my config:

PYTHON_PATH=/usr/bin/python3
DIR=/home/pi/domoticz/plugins/HomeConnect
DAEMON=$DIR/homeconnectSSE.py
DEVICE_NAME=Oven
DOMOTICZ_IP=172.19.3.212
DOMOTICZ_PORT=8001
DAEMON_NAME=homeconnectSSE_$DEVICE_NAME
DAEMON_LOG=/home/pi/domoticz/plugins/HomeConnect/Log/$DAEMON_NAME.log
# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you ar using the Raspberry Pi GPIO from Python.
DAEMON_USER=username

**Comment by mario-peters** [comment]
hmm, i will try to change is in the next version.
