### ISSUE TITLE
sharing homeconnectSSE.sh

### ISSUE THREAD

**Issue by knights1** [mario-peters/Domoticz-Home-Connect-Plugin#14]
Can someone share their config file for the homeconnectSSE.sh. Having trouble filling in the right. Below doesnt work (sorry voor de noob question)

# Change the next 3 lines to suit where you install your script and what you want to call it
PYTHON_PATH=/usr/local/lib/python2.7
DIR=~/domoticz/plugins/HomeConnect
DAEMON=$DIR/homeconnectSSE.py
DEVICE_NAME=Washer
DOMOTICZ_IP=192.168.1.91
DOMOTICZ_PORT=5555
DAEMON_NAME=homeconnectSSE_$DEVICE_NAME
DAEMON_LOG=<log location>$DAEMON_NAME.log

**Comment by LorDHarA** [comment]
This is what I have, it is working fine.

PYTHON_PATH=/usr/bin/python3
DIR=/home/pi/domoticz/plugins/HomeConnect
DAEMON=$DIR/homeconnectSSE.py
DEVICE_NAME=Oven
DOMOTICZ_IP=172.19.3.212
DOMOTICZ_PORT=8001
DAEMON_NAME=homeconnectSSE_$DEVICE_NAME
DAEMON_LOG=/home/pi/domoticz/plugins/HomeConnect/Log/$DAEMON_NAME.log
