### ISSUE TITLE
port settings

### ISSUE THREAD

**Issue by geezerrr** [mario-peters/Domoticz-Home-Connect-Plugin#5]
Dear Mario,

found your plugin this morning but i cant get it to work on a raspi 3, buster running domoticz .
i was not sure what to set by "port" in domoticz

can you please advice? 

thnx in advance.

**Comment by mario-peters** [comment]
The plugin functions as a 2-stage package. Plugin.py is actually a web service that waits for commands from homeconnectSSE.sh, which you run in the background as a separate Linux service. This service sends http commands to plugin.py. The requested port is therefore the tcp port on which the plugin is listening. Could it be that you have not opened the port in the Linux firewall?

In addition, you have to edit the homeconnectSSE.sh file to start it (after adding the plugin). Here too you have to fill in the Domoticz port number, which you entered with the plugin.

Are you going to take this further?

**Comment by mario-peters** [comment]
As indicated on the Domoticz forum I would like to describe this in more detail on the wiki.

**Comment by geezerrr** [comment]
thanks for your answer, i will give it a try and see how far i get.
ill let you know.

**Comment by mario-peters** [comment]
I changed the wiki page.
With help of this info, you must be able to use the plugin.
I will close this issue.
If you still have questions, please let me know.
