### ISSUE TITLE
Error line 101 plugin.py when no icons available.

### ISSUE THREAD

**Issue by GeitjeG** [mario-peters/Domoticz-Home-Connect-Plugin#6]
I think because I have no specific icons for the plugin, I get an error in line 101 of plugin.py.

In line 101 of plugin.py code should be different I think?
`Domoticz.Device(Name="Operation state", Unit=1, TypeName="Text", Image=Images[self.HOMECONNECT_ICON].ID).Create()`
should be:
`Domoticz.Device(Name="Operation state", Unit=1, TypeName="Text").Create()`

I changed it this way an the error is gone. I have no error so far. Devices are created (but this time I had to manually add them from devices tab to Utility/Temperature tab. This is no problem of course. My oven has not been used since, I will check it soon.

**Comment by mario-peters** [comment]
Fixed in the next commit.
