### ISSUE TITLE
Multiple Ovens

### ISSUE THREAD

**Issue by LorDHarA** [mario-peters/Domoticz-Home-Connect-Plugin#9]
Hello mario,

I have the Home connect plugin running succesfully, it is working. Only thing is: I have two ovens: a microwave/oven and a baking oven. Now it only sees/is connecting the Microwave/Oven. How can i connect both ovens? What should I do?

regards
Harald

**Comment by mario-peters** [comment]
I think this isn't possible with the current software, but I understand your situation.
Will add this to the ToDo-list and keep you informed about the progress on this new feature.
